// <auto-generated />
using System;
using EfCoreFilterProjectionBug;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfCoreFilterProjectionBug.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("EfCoreFilterProjectionBug.Child", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("EfCoreFilterProjectionBug.GrandChild", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("GrandChildren");
                });

            modelBuilder.Entity("EfCoreFilterProjectionBug.Parent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChildId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.ToTable("Parents");
                });

            modelBuilder.Entity("EfCoreFilterProjectionBug.GrandChild", b =>
                {
                    b.HasOne("EfCoreFilterProjectionBug.Child", null)
                        .WithMany("GrandChildren")
                        .HasForeignKey("ChildId");
                });

            modelBuilder.Entity("EfCoreFilterProjectionBug.Parent", b =>
                {
                    b.HasOne("EfCoreFilterProjectionBug.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("EfCoreFilterProjectionBug.Child", b =>
                {
                    b.Navigation("GrandChildren");
                });
#pragma warning restore 612, 618
        }
    }
}
